[package]
name = "regex-ffi"
version = "0.1.0"
authors = ["Doug Thayer <dothayer@mozilla.com>"]
edition = "2018"
license = "MPL-2.0"

[dependencies]
regex = "1"
nsstring = { path = "../../../xpcom/rust/nsstring" }
